language: python

python:
  - "3.6.5"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'ALTER USER postgres WITH PASSWORD challenge;' -U pastgres

script:
  - py.test --cov api/views

after_success:
  - coveralls