language: python

python:
  - "3.6.5"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database d4eo92qumfels6;' -U rydoowkieaxjhfs

script:
  - py.test --cov api

after_success:
  - coveralls